on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
name: Code quality
jobs:
  vue-tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run vue-tsc
        run: npm run analyze
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run vue-tsc
        run: npm run lint
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Run vue-tsc
        run: npm run test
  test-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Create folder for testing
        run: mkdir dist
      - name: Install dependencies
        run: cd infrastructure && npm ci
      - name: Run vue-tsc
        run: cd infrastructure && npm run test